name: Workflow-Ducks-Shop.

on:
  push:
    branches:
      - dev

env:
  ENVIRONMENT: "develop"
  STATE_KEY: "Tfstate-ducks-server"
  ECR_REGISTRY_URI: "658299583140.dkr.ecr.us-east-1.amazonaws.com/duck-shop-0.1"
  AWS_PROFILE: "AWS"
  BUCKET_NAME: "tf-state-ducks-develop"
jobs:
  set-up-terraform-backend:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
              
      - name: Configure AWS Credentials
        id: config_aws_creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      
      - name: terraform-backend-set-up
        uses: ./.github/actions/terraform-backend    

      - name: Terraform-Init 
        id: tf-init
        run: |
          export BUCKET_NAME="tf-state-ducks-${ENVIRONMENT}"
          export DYNAMODB_TABLE="dynamodb-ducks-${ENVIRONMENT}"
          export AWS_REGION="us-east-1"
          terraform init \
          -backend-config="bucket=${BUCKET_NAME}" \
          -backend-config="region=${AWS_REGION}" \
          -backend-config="key=${STATE_KEY}" \
          -backend-config="dynamodb_table=${DYNAMODB_TABLE}"
            
      - name: Terraform-Plan
        id: tf-plan
        run: |
            terraform plan \
            -input=false \
            -out tfplan

      - name: Build Docker Image
        id: build-image
        run: |
          docker build -t ${{ env.ECR_REGISTRY_URI }}/my-app:${{ github.sha }} ./find_api
          echo "::set-output name=image_uri::${{ env.ECR_REGISTRY_URI }}/my-app:${{ github.sha }}"
    
      - name: Authenticate with AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 --profile ${{ env.AWS_PROFILE }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY_URI }}
      
      - name: Push to AWS ECR
        run: |
          docker push ${{ steps.build-image.outputs.image_uri }}
