name: workflow-build-app

on:
  push:
    branches:
      - dev
    paths:
      - 'find_api/**'
      - 'docker/**'
env:
  ENVIRONMENT: "develop"
  ECR_REGISTRY_URI: "658299583140.dkr.ecr.us-east-1.amazonaws.com/duck-shop-0.1"
  
jobs:
   set-up-terraform-backend:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
              
      - name: Configure AWS Credentials
        id: config_aws_creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      
      - name: terraform-backend-set-up
        uses: ./.github/actions/terraform-backend    

      - name: Authenticate with AWS ECR
        run: |
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 658299583140.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Build Docker Image
        id: build-image
        run: |
           docker build -t ${{ env.ECR_REGISTRY_URI }}:${{ github.sha }} ./find_api
           
      - name: Push to AWS ECR
        run: |
           docker push ${{ env.ECR_REGISTRY_URI }}:${{ github.sha }}
          
