name: workflow-build-app

on:
  push:
    branches:
      - dev
    paths:
      - 'find_api/**'
      - 'docker/**'

env:
  ENVIRONMENT: "develop"
  ECR_REGISTRY_URI: "658299583140.dkr.ecr.us-east-1.amazonaws.com/ecr-develop"
  ECS_CLUSTER_NAME: "cluster_develop"
  ECS_SERVICE_NAME: "task_def_develop"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Authenticate with AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 658299583140.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY_URI:${IMAGE_TAG} ./docker
          docker push $ECR_REGISTRY_URI:${IMAGE_TAG}
          docker tag $ECR_REGISTRY_URI:${IMAGE_TAG} $ECR_REGISTRY_URI:latest
          docker push $ECR_REGISTRY_URI:latest
          